### ISSUE TITLE
Unable use with vue-3, selfhook.call is not a function

### ISSUE THREAD

**Issue by kinetre** [grid-js/gridjs-vue#112]
Probably a vue-3 issue, but...

Using the Basic example from the npm page, [https://www.npmjs.com/package/gridjs-vue](Page)

Vue throws....Uncaught TypeError: selfHook.call is not a function
    at callSyncHook (runtime-core.esm-bundler.js?5c40:5435)
    at applyOptions (runtime-core.esm-bundler.js?5c40:5227)
    at finishComponentSetup (runtime-core.esm-bundler.js?5c40:6006)
    at setupStatefulComponent (runtime-core.esm-bundler.js?5c40:5942)
    at setupComponent (runtime-core.esm-bundler.js?5c40:5882)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4161)
    at processComponent (runtime-core.esm-bundler.js?5c40:4137)
    at patch (runtime-core.esm-bundler.js?5c40:3784)
    at componentEffect (runtime-core.esm-bundler.js?5c40:4258)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)

**Comment by RokasBagdonas** [comment]
Any updates on this? I am using:
"gridjs-vue": "^3.2.2",
"vue": "^3.0.0"

**Comment by zp4rand0miz31** [comment]
Hi, same problem here with :
"gridjs-vue": "^3.2.3" & vue 3.0.0

**Comment by afshinm** [comment]
Sorry this issue was closed automatically. 

I'm not quite sure what's the correct solution here as my knowledge about Vue is very limited. @selfagency initially wrote this wrapper, they might have a better answer.

**Comment by OliverLeitner** [comment]
ive got a similiar problem with current vue 3.0.6

[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next 
  at <Grid cols= 
Array(4) [ "Name", "First Name", "Last Name", "Address" ]
 rows= 
Array []
 > 
  at <DataGridComponent> 
  at <DataGridView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

caused in/by: runtime-core.esm-bundler.js:38

----------------------------------------------------------------------

17:17:27.450 Uncaught (in promise) TypeError: selfHook.bind is not a function
    callSyncHook runtime-core.esm-bundler.js:5957
    applyOptions runtime-core.esm-bundler.js:5709
    finishComponentSetup runtime-core.esm-bundler.js:6574
    setupStatefulComponent runtime-core.esm-bundler.js:6505
    setupComponent runtime-core.esm-bundler.js:6445
    mountComponent runtime-core.esm-bundler.js:4151
    processComponent runtime-core.esm-bundler.js:4127
    patch runtime-core.esm-bundler.js:3745
    mountChildren runtime-core.esm-bundler.js:3927
    mountElement runtime-core.esm-bundler.js:3850
    processElement runtime-core.esm-bundler.js:3822
    patch runtime-core.esm-bundler.js:3742
    mountChildren runtime-core.esm-bundler.js:3927
    mountElement runtime-core.esm-bundler.js:3850
    processElement runtime-core.esm-bundler.js:3822
    patch runtime-core.esm-bundler.js:3742
    componentEffect runtime-core.esm-bundler.js:4243
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4208
    mountComponent runtime-core.esm-bundler.js:4167
    processComponent runtime-core.esm-bundler.js:4127
    patch runtime-core.esm-bundler.js:3745
    mountChildren runtime-core.esm-bundler.js:3927
    mountElement runtime-core.esm-bundler.js:3850
    processElement runtime-core.esm-bundler.js:3822
    patch runtime-core.esm-bundler.js:3742
    componentEffect runtime-core.esm-bundler.js:4243
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4208
    mountComponent runtime-core.esm-bundler.js:4167
    processComponent runtime-core.esm-bundler.js:4127
    patch runtime-core.esm-bundler.js:3745
    componentEffect runtime-core.esm-bundler.js:4313
    reactiveEffect reactivity.esm-bundler.js:42
    callWithErrorHandling runtime-core.esm-bundler.js:154
    flushJobs runtime-core.esm-bundler.js:384
    promise callback*queueFlush runtime-core.esm-bundler.js:286
    queueJob runtime-core.esm-bundler.js:280
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    scheduler reactivity.esm-bundler.js:820
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    scheduler reactivity.esm-bundler.js:820
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    scheduler reactivity.esm-bundler.js:820
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    set value reactivity.esm-bundler.js:730
    finalizeNavigation vue-router.esm-bundler.js:3071
    pushWithRedirect vue-router.esm-bundler.js:2944
    promise callback*pushWithRedirect vue-router.esm-bundler.js:2915
    push vue-router.esm-bundler.js:2849
    install vue-router.esm-bundler.js:3226
    use runtime-core.esm-bundler.js:2972
    <anonymous> main.ts:10
    ts app.js:1217
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1302
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonymous> app.js:994
    <anonymous> app.js:997
runtime-core.esm-bundler.js:5957
    flushJobs runtime-core.esm-bundler.js:397
    (Async: promise callback)
    queueFlush runtime-core.esm-bundler.js:286
    queueJob runtime-core.esm-bundler.js:280
    run reactivity.esm-bundler.js:183
    forEach self-hosted:4324
    trigger reactivity.esm-bundler.js:189
    scheduler reactivity.esm-bundler.js:820
    run reactivity.esm-bundler.js:183
    forEach self-hosted:4324
    trigger reactivity.esm-bundler.js:189
    scheduler reactivity.esm-bundler.js:820
    run reactivity.esm-bundler.js:183
    forEach self-hosted:4324
    trigger reactivity.esm-bundler.js:189
    scheduler reactivity.esm-bundler.js:820
    run reactivity.esm-bundler.js:183
    forEach self-hosted:4324
    trigger reactivity.esm-bundler.js:189
    set value reactivity.esm-bundler.js:730
    finalizeNavigation vue-router.esm-bundler.js:3071
    pushWithRedirect vue-router.esm-bundler.js:2944
    (Async: promise callback)
    pushWithRedirect vue-router.esm-bundler.js:2915
    push vue-router.esm-bundler.js:2849
    install vue-router.esm-bundler.js:3226
    use runtime-core.esm-bundler.js:2972
    <anonym> main.ts:10
    ts app.js:1217
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1302
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonym> app.js:994
    <anonym> app.js:997
---------------------------------------------------------------------------

thanks in advance for any kinda help you may provide to me...

didnt want to go straight to vuejs, after all, ive heard, that they dont support 3rd party stuff...
