### ISSUE TITLE
export 'h' was not found in 'gridjs-vue'

### ISSUE THREAD

**Issue by aprilahijriyan** [grid-js/gridjs-vue#175]
Hi, why is the 'h' function not found in vue?

Is the 'h' function only available in reactjs? can you implement in vue? It might be more useful, for example, to create custom cells as in the documentation.

Thank you in advance.

**Comment by waleev** [comment]
Did you see this helper?
https://github.com/grid-js/gridjs-vue#gridjsh

**Comment by aprilahijriyan** [comment]
Ahhh, sorry, my bad. 😄
