### ISSUE TITLE
How to use $router in $gridjs.render

### ISSUE THREAD

**Issue by aprilahijriyan** [grid-js/gridjs-vue#182]
Hi,

I'm using the nuxtjs framework here and I'm trying to use my component https://pastebin.com/TvyL6Lm7 for the actions column using $gridjs.render.

But, I can't use $router for route navigation.

Thank you in advance.

**Comment by ChubatajaMaria** [comment]
Ran into same problem today. The router-link was not rendered inside the cell.

**Comment by selfagency** [comment]
As of #368, `$gridjs.render` has been killed-off in favor of a new function, `$gridjs.helper`, that hopefully resolves the plethora of issues with `$gridjs.render`. 

Usage:

```js
const components = { MyComponent }
const template = `<my-component :content="content"></my-component>`
const data = {
  content: '🥳'
}

this.$gridjs.helper(components, template, data)
```

Example:

```js
export default {
  data() {
    return {
      columns: [
        {
          name: 'Name',
          formatter: cell =>
            this.$gridjs.helper({ MyComponent }, `<my-component :content="content"></my-component>`, { content: cell })
        }
      ]
    }
  }
}
```
