### ISSUE TITLE
How to access the "grid" instance and work with its events

### ISSUE THREAD

**Issue by asilverstein** [grid-js/gridjs-vue#214]
**Describe the bug**
I'm unable to figure out how to access the "grid" object that represents the `<grid> `element in my component. This object is mentioned in various places in the docs (e.g., https://gridjs.io/docs/examples/selection-events/) but not in a Vue context.

**To Reproduce**
1. Add a `<grid>` component with a ref attribute, such as` <grid ref="memberGrid"/>` (with all the other required properties and so on -- the grid itself works fine)
2. In `mounted` method of my component, attempt to access the grid instance, such as `const grid = this.$refs.memberGrid;`
3. Try to use the `on` method of the grid, for example: `grid.on('ready', () => {})`
4. Error message: _TypeError: grid.on is not a function_

**Expected behavior**
Able to access the `grid` instance in my Vue component. _Note_: Using `refs` was just a best guess of how this might work (docs are not explicit on how to do this, hence this issue).

**Comment by goellner** [comment]
struggling with this exact thing myself. would be great to have an example of this in the documentation

**Comment by selfagency** [comment]
You can give the Vue component a `ref` attribute and then access the Grid instance via `this.$refs`.

```html
<template>
  <grid :columns="columns" :rows="rows" ref="myGrid"></grid>
</template>

<script>
export default {
  mounted() {
    this.$nextTick() {
      this.$refs.myGrid.grid.updateConfig({ search: true; }).forceRender();
    }
  }
}
</script>
```
