### ISSUE TITLE
Ready event

### ISSUE THREAD

**Issue by anujchhabria1** [grid-js/gridjs-vue#220]
Is there a 'ready' event on the vue package? I did see it on the gridjs package, but when I use on '@ready' on vue, it's not fired. 

Is there any other way to manipulate the HTML once gridjs has rendered?

**Comment by goellner** [comment]
This is related I think: https://github.com/grid-js/gridjs-vue/issues/129

**Comment by anujchhabria1** [comment]
@goellner Doesn't look like the package has support for it, submitted a pull requet.

**Comment by selfagency** [comment]
Thanks for your suggestion. As of #368, there is a `@ready` event trigger available on the component.
