### ISSUE TITLE
tr cannot be customized via class

### ISSUE THREAD

**Issue by mrtampan** [grid-js/gridjs-vue#245]
I want to create a striped table, I try to enter a class like this:

file scss. index.scss:
![1231231](https://user-images.githubusercontent.com/33930946/108724978-7e366d00-7558-11eb-970d-b7a109d5ed95.PNG)

file index.vue
![12312312](https://user-images.githubusercontent.com/33930946/108725074-95755a80-7558-11eb-9b93-b0b621cb35ab.PNG)

![1231](https://user-images.githubusercontent.com/33930946/108724938-75de3200-7558-11eb-9f47-8a789bb3c6e1.PNG)

but nothing happened. i dont know, why tr cannot set class..
thank you

**Comment by selfagency** [comment]
This issue is resolved in #368, which fixes all the outstanding issues with `className` and `styles`.
