### ISSUE TITLE
onclick create an re-render & redirect to the first page of pagination

### ISSUE THREAD

**Issue by njiva-niaina** [grid-js/gridjs-vue#266]
The bug occurs when I click on a button in one of my columns: the table is completely reloaded.
If I'm on page 2, 3, 4 ... of the table (via pagination), everything reloads and I don't stay on my page, but i'm back on the first page.

**Expected behavior**
That the table does not reload if we do not modify the data of the table, that I stay on the page (pagination) that I have chosen

**Screenshots**
![image](https://user-images.githubusercontent.com/60059260/110447208-0bd59900-80d1-11eb-8e3f-adf63eb5ff23.png)
![image](https://user-images.githubusercontent.com/60059260/110447260-1abc4b80-80d1-11eb-8e84-fe6959573b99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version : 88.0

Thanks

**Comment by selfagency** [comment]
Please wait until #368 is merged and released. Then try again and let me know if the issue persists. Thanks.

**Comment by selfagency** [comment]
You can try the pre-release `5.0.2-0` now!
