### ISSUE TITLE
Library seems to require global registration

### ISSUE THREAD

**Issue by taobojlen** [grid-js/gridjs-vue#397]
**Describe the bug**
I get an error when attempting to import the `Grid` component in just one place. The error is resolved by registering the plugin globally.

**To Reproduce**
1. Import  the library via `import { Grid } from "gridjs-vue/dist/index.umd.js"`
2. Attempt to render a table
3. See a `TypeError: this.$gridjs is undefined` error in the console. The table fails to render.
4. Import `GridGlobal` and add the line `Vue.use(GridGlobal)` to resolve the error.

**Expected behavior**
Local registration, as in the Grid.js docs (https://gridjs.io/docs/integrations/vue), works.
This could also be resolved by updating the docs on that link to remove the local registration option?

**Additional context**
Using gridjs-vue@5.0.2-3.

**Comment by brianboyko** [comment]
I'm running into the same error as well.
