### ISSUE TITLE
vue 2.9.6 cant use this lib

### ISSUE THREAD

**Issue by silencesky001** [grid-js/gridjs-vue#408]
i followed the girdjs.io example , installed gridjs.
when i entered npm run dev . display this .

ERROR  Failed to compile with 3 errors                                                                                                                                                                                     5:55:29 ├F10: PM┤
These dependencies were not found:

* https://unpkg.com/gridjs@5.0.1/dist/gridjs.module.js in ./node_modules/_gridjs-vue@5.0.1@gridjs-vue/dist/index.esm.js
* https://unpkg.com/parse-css-stylesheet/index.js in ./node_modules/_gridjs-vue@5.0.1@gridjs-vue/dist/index.esm.js
* https://unpkg.com/uid/single/index.mjs in ./node_modules/_gridjs-vue@5.0.1@gridjs-vue/dist/index.esm.js

**Comment by Tragio** [comment]
@selfagency I'm also facing this issues. Do you have any workaround? 🙂

**Comment by simion-chis** [comment]
I have the same issue. I'm trying to use this package into a laravel app

"vue": "^2.5.17",
"gridjs": "^5.0.1",
"gridjs-vue": "^5.0.1",

` ERROR  Failed to compile with 3 errors                                                              12:22:33 PM

These dependencies were not found:

* https://unpkg.com/gridjs@5.0.1/dist/gridjs.module.js in ./node_modules/gridjs-vue/dist/index.esm.js
* https://unpkg.com/parse-css-stylesheet/index.js in ./node_modules/gridjs-vue/dist/index.esm.js
* https://unpkg.com/uid/single/index.mjs in ./node_modules/gridjs-vue/dist/index.esm.js`
