### ISSUE TITLE
server and pagination props not reactive

### ISSUE THREAD

**Issue by cocolee** [grid-js/gridjs-vue#94]
Hi;

I'm implement table prop like below code. and i have row limit select input when i was change rowlimit i'm using change method and i'm change like this.pagination.limit = val but table is not update. I hope i can explain myself.

```
   {
        url: '',
        headers: {
          Authorization: `Bearer ${this.$store.getters['auth/token']}`
        },
        // eslint-disable-next-line no-undef
        then: (res) =>
          res.Data.map((data) => [
            this.$moment(data.TimeStamp).format('DD-MM-YYYY HH:mm'),
            `${data.CoinFromCode}/${data.CoinToCode}`,
            this.$gridjs.html(
              this.$options.filters.currency(data.Amount, {
                symbol: data.CoinToCode,
                thousandsSeparator: '.',
                fractionCount: this.$fchelpers.moneyFractionCount(
                  data.CoinToCode
                ),
                fractionSeparator: ',',
                symbolPosition: '',
                symbolSpacing: true
              })
            ),
            this.$gridjs.html(
              this.$options.filters.currency(data.OrderValue, {
                symbol: data.CoinFromCode,
                thousandsSeparator: '.',
                fractionCount: this.$fchelpers.moneyFractionCount(
                  data.CoinFromCode
                ),
                fractionSeparator: ',',
                symbolPosition: '',
                symbolSpacing: true
              })
            )
          ]),
        handle: (res) => {
          // no matching records found
          if (res.status === 404) {
            return { data: [] }
          } else if (res.status === 401) {
            throw new Error('oh no :(')
          }
          if (res.ok) return res.json()
        },
        total: (res) => res.Data[0].total
      },
      pagination: {
        limit: 20,
        summary: false,
        server: {
          url: (prev, page, limit) => {
            return `${prev}&RowLimit=${limit}&PageNumber=${1 * (page + 1)}`
          }
        }
      }
  }
```

**Comment by thomasc1337** [comment]
I have the same issue:

The bellow code is from the example page and I just added pagination, but it doesn't do pagination.

```
<template>
  <grid :cols="cols" :rows="rows"></grid>
</template>

<script>
  import Grid from 'gridjs-vue'

  export default {
    name: 'Cars',
    components: {
      Grid
    },
    data() {
      return {
        cols: ['Make', 'Model', 'Year', 'Color'],
        pagination: {
          limit: 1
        },
        rows: [
          ['Ford', 'Fusion', '2011', 'Silver'],
          ['Chevrolet', 'Cruz', '2018', 'White']
        ]
      }
    }
  }
</script>
```

**Comment by cocolee** [comment]
> I have the same issue.
> 
> The code below is from the example page and I just added pagination, but it doesn't do pagination:
> 
> ```js
> <template>
>   <grid :cols="cols" :rows="rows"></grid>
> </template>
> 
> <script>
>   import Grid from 'gridjs-vue'
> 
>   export default {
>     name: 'Cars',
>     components: {
>       Grid
>     },
>     data() {
>       return {
>         cols: ['Make', 'Model', 'Year', 'Color'],
>         pagination: {
>           limit: 1
>         },
>         rows: [
>           ['Ford', 'Fusion', '2011', 'Silver'],
>           ['Chevrolet', 'Cruz', '2018', 'White']
>         ]
>       }
>     }
>   }
> </script>
> ```

Hi @thomasc1337 

You should add :pagination="pagination" prop to your grid component like below code by the way sorry for late answer =/

`<grid :cols="cols" :rows="rows" :pagination="pagination"></grid>`

**Comment by Yauheni80** [comment]
pagination: {
                    required: true,
                    limit: 1
                },

**Comment by thomasc1337** [comment]
> Hi @thomasc1337
> 
> You should add :pagination="pagination" prop to your grid component like below code by the way sorry for late answer =/
> 
> `<grid :cols="cols" :rows="rows" :pagination="pagination"></grid>`

Ah, got it, thanks @cocolee.

**Comment by cocolee** [comment]
> > Hi @thomasc1337
> > You should add :pagination="pagination" prop to your grid component like below code by the way sorry for late answer =/
> > `<grid :cols="cols" :rows="rows" :pagination="pagination"></grid>`
> 
> Ah, got it, thanks @cocolee.

Your welcome @thomasc1337
